# Local development helpers. Run `make help` for the list.
DEV := docker compose -f docker-compose.dev.yml

.PHONY: help dev-up dev-up-build dev-down dev-logs dev-ps dev-restart dev-psql headers migrate migration migrate-down db-stamp hooks skill-scan skill-audit

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

hooks: ## Install the git pre-commit hooks (ruff + mypy, mirrors CI)
	uv run pre-commit install

skill-scan: ## Vet an agent skill before installing it: make skill-scan target=<path|url>
	@test -n "$(target)" || { echo 'usage: make skill-scan target=<path|url>'; exit 2; }
	tools/skill-scan.sh "$(target)"

skill-audit: ## Scan every agent skill installed under ~/.claude
	tools/skill-scan.sh --installed

dev-up: ## Start the local stack (db + all apps, hot-reload) and apply migrations
	$(DEV) up -d
	$(MAKE) migrate

# Migrations run inside an app container: it already has the code, the alembic
# dependency, and DATABASE_URL pointed at the db service. Autogenerated files
# land back on the host through the .:/app bind mount.
migrate: ## Apply all pending migrations (alembic upgrade head)
	$(DEV) run --rm strava-api alembic upgrade head

migrate-down: ## Roll back the most recent migration
	$(DEV) run --rm strava-api alembic downgrade -1

migration: ## Autogenerate a migration from model changes: make migration name="add foo"
	$(DEV) run --rm strava-api alembic revision --autogenerate -m "$(name)"

db-stamp: ## Adopt Alembic on a DB that already has the tables (one-time): stamp it at head
	$(DEV) run --rm strava-api alembic stamp head

dev-up-build: ## Rebuild images then start (use after changing requirements.txt/Dockerfile)
	$(DEV) up -d --build

dev-down: ## Stop the stack (keeps the db volume)
	$(DEV) down

dev-logs: ## Tail logs from all services
	$(DEV) logs -f

dev-ps: ## Show running services
	$(DEV) ps

dev-restart: ## Restart all app containers
	$(DEV) restart

dev-psql: ## Open a psql shell on the dev database
	$(DEV) exec db psql -U $${POSTGRES_USER:-backend_user} -d $${POSTGRES_DB:-backend_db}

headers: ## Curl security headers from each running app
	@for p in 5001 5002 5004 5005; do \
		echo "--- localhost:$$p ---"; \
		curl -s -D - -o /dev/null http://localhost:$$p/ 2>/dev/null | \
		grep -iE 'content-security-policy|x-frame-options|x-content-type-options|strict-transport-security|cache-control' || echo "  (no response)"; \
	done
